version: '3.8'

services:
  # 1. FastAPI App
  app:
    build: .
    container_name: moviehub-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=mysql+aiomysql://root:db_password@db/moviehub_db
      - REDIS_URL=redis://redis:6379/0
      - TMDB_API_KEY=${TMDB_API_KEY}
    depends_on:
      - db
      - redis
    networks:
      - moviehub-network

  # 2. MySQL DB
  db:
    image: mysql:8.0
    container_name: moviehub-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db_password
      MYSQL_DATABASE: moviehub_db
    ports:
      - "3307:3306" 
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - moviehub-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # 3. Redis Cache
  redis:
    image: redis:alpine
    container_name: moviehub-redis
    ports:
      - "6379:6379"
    networks:
      - moviehub-network

volumes:
  db_data:

networks:
  moviehub-network:
    driver: bridge